#!/usr/bin/env python3
"""Extract the firmware's SD/FatFs disk-layer functions VERBATIM from
firmware/firmware.c into fw_fs_extracted.c, so the host harness tests the
exact code that ships in the bitstream (sync-by-construction; same idea as
the sim_core/ copies, but automated so it can't drift).

Extracted functions (in firmware order, which satisfies call dependencies):
  mount_atr, atr_read_sector, atr_write_sector, atr_format, create_blank_atr
Globals they use are declared by the harness, not extracted.
"""
import re, sys, pathlib

SRC = pathlib.Path(__file__).resolve().parents[2] / "firmware" / "firmware.c"
OUT = pathlib.Path(__file__).resolve().parent / "fw_fs_extracted.c"

FUNCS = ["mount_atr", "atr_read_sector", "atr_write_sector",
         "atr_format", "create_blank_atr",
         "bridge_mkdirs", "bridge_put_open", "bridge_put_chunk", "bridge_put_close",
         "hdd_path", "hdd_open", "hdd_read", "hdd_write", "hdd_close",
         "hdd_status", "hdd_delete", "hdd_rename"]

src = SRC.read_text()

def extract(name):
    # signature line like "int mount_atr(char *filepath, int slot) {"
    m = re.search(rf'^\w[\w \t\*]*\b{name}\s*\([^)]*\)\s*\{{', src, re.M)
    if not m:
        sys.exit(f"extract_fw_fs: cannot find function {name} in {SRC}")
    i = m.end() - 1          # at the opening brace
    depth = 0
    j = i
    while True:
        c = src[j]
        if c == '{': depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0:
                return src[m.start():j+1]
        j += 1

parts = ["/* AUTO-GENERATED by extract_fw_fs.py — DO NOT EDIT.",
         f" * Source of truth: firmware/firmware.c (functions: {', '.join(FUNCS)})",
         " */\n"]
for f in FUNCS:
    parts.append(extract(f))
    parts.append("")
OUT.write_text("\n".join(parts))
print(f"extracted {len(FUNCS)} functions -> {OUT.name}")
