// fw_bram.v — PicoRV32 firmware boot RAM in on-chip BSRAM (firmware-off-SDRAM).
//
// 16384 x 32-bit = 64 KB, byte-laned: 4 independent byte-wide memories (one per
// mem_wstrb bit) so per-byte writes (.data/.bss/stack) work natively and Gowin
// infers clean BSRAM. Each lane is $readmemh-initialised from fw_laneN.hex
// (generated by firmware/bin2bram.py).
//
// Why byte lanes (not one 32-bit array with a mask): a single wide array with a
// partial-write mask infers as registers or read-modify-write logic on Gowin;
// 4 byte-wide arrays with simple "if (we) mem[a]<=di" each map directly to BSRAM.
//
// Read: registered → data valid 1 cycle after the access is presented. `ready`
// is asserted that same cycle (1-cycle access), matching the PicoRV32 mem bus.
//
// Reset-live by construction: the read path is driven by the live CPU address and
// reaches mem_rdata (used by the CPU), so synthesis cannot prune it — this is the
// pattern the de-risking probe confirmed Gowin retains (no DFF explosion).
//
// IMPORTANT: this module has NO flash_loaded / valid gate that an optimizer can
// constant-fold to prove the read path dead. That gate is what made the prior
// feature/picorv32-bram-firmware attempt get its BSRAM pruned.

module fw_bram #(
    parameter AWORDS = 16384,          // depth in 32-bit words (64 KB)
    parameter AW     = 14              // clog2(AWORDS)
)(
    input  wire        clk,
    input  wire        sel,            // access requested this cycle
    input  wire [AW-1:0] waddr,        // word address
    input  wire [31:0] wdata,
    input  wire [3:0]  wstrb,          // per-byte write enables (0000 = read)
    output reg  [31:0] rdata,          // registered, valid 1 cycle after sel
    output reg         ready           // 1-cycle ack, aligned with rdata
);
    // Four byte-wide memories, each its own BSRAM lane.
    reg [7:0] mem0 [0:AWORDS-1];
    reg [7:0] mem1 [0:AWORDS-1];
    reg [7:0] mem2 [0:AWORDS-1];
    reg [7:0] mem3 [0:AWORDS-1];

    initial begin
        $readmemh("fw_lane0.hex", mem0);
        $readmemh("fw_lane1.hex", mem1);
        $readmemh("fw_lane2.hex", mem2);
        $readmemh("fw_lane3.hex", mem3);
    end

    always @(posedge clk) begin
        // Per-byte synchronous write
        if (sel & wstrb[0]) mem0[waddr] <= wdata[7:0];
        if (sel & wstrb[1]) mem1[waddr] <= wdata[15:8];
        if (sel & wstrb[2]) mem2[waddr] <= wdata[23:16];
        if (sel & wstrb[3]) mem3[waddr] <= wdata[31:24];

        // Registered read (read-first not required: PicoRV32 never reads the same
        // word it writes in the same cycle on this bus).
        rdata <= {mem3[waddr], mem2[waddr], mem1[waddr], mem0[waddr]};

        // 1-cycle ready, aligned with the registered rdata.
        ready <= sel;
    end
endmodule
